---
# tasks file for centosGrafana
- name: Add grafana rpm key
  rpm_key:
    key: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_facts['distribution'] == 'CentOS'

- name: Add grafana repository
  yum_repository:
    name: grafana
    description: Adds the repository of grafana
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: True
    gpgkey: https://packages.grafana.com/gpg.key
  when: ansible_facts['distribution'] == 'CentOS'

- name: Install grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == 'CentOS'

- name: Install Nginx
  package:
    name: nginx
    state: latest
    update_cache: yes

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Create etc prometheus directory
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Create var lib prometheus directory
  file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'

- name: Create var log prometheus directory
  file:
    path: /var/log/prometheus
    state: directory
    mode: '0755'

- name: Create var run prometheus
  file:
    path: /var/run/promotheus
    state: directory
    mode: '0755'

- name: Download and unarchive prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.2.1/prometheus-2.2.1.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
  register: prometheus_archive

- name: Copy prometheus to bin
  shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus /usr/local/bin/"
  # when: prometheus_archive.changed

- name: Copy promtool to bin
  shell: "cp /tmp/prometheus-2.2.1.linux-amd64/promtool /usr/local/bin/"
  # when: prometheus_archive.changed

- name: Make prometheus executable
  file:
    path: /usr/local/bin/prometheus
    mode: u+x,g+x,o+x

- name: Make promtool executable
  file:
    path: /usr/local/bin/promtool
    mode: u+x,g+x,o+x

- name: Copy prometheus to etc
  shell: "cp -r /tmp.prometheus-2.2.1.linux-amd64/prometheus.yml /etc/prometheus/"
  when: prometheus_archive.changed

- name: Copy consoles to etc
  shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/consoles /etc/prometheus/"
  # when: prometheus_archive.changed

- name: Copy console library to etc
  shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/console_libraries /etc/prometheus/"
  # when: prometheus_archive.changed

- name: Copy prometheus system service
  copy:
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=root
      Group=root
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file /etc/prometheus/prometheus.yml \
        --storage.tsdb.path /var/lib/prometheus \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/promotheus/console_libraries
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service
    mode: '0755'

- name: Start and enable service
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Add influxdb repo
  copy: 
    src: influxdb.repo
    dest: /etc/yum.repos.d/

- name: Install influxdb
  package:
    name: influxdb
    state: latest
    update_cache: yes

- name: Run influxdb
  service:
    name: influxdb
    state: started
