---
# tasks file for ubuntuNagios1
- name: Install nagios core requisites
  apt:
    name:
      - build-essential
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gd
      - libgd-dev
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
      - wget
      - apache2-utils
      - unzip
  when: ansible_facts['distribution'] == "Ubuntu"
- name: add group nagcmd
  group:
    name: nagcmd
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: add user nagios
  user:
    name: nagios
    group: nagcmd
  when: ansible_facts['distribution'] == "Ubuntu"
