---
# tasks file for ubuntuGrafana
- name: Install grafana packages
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add grafana GPG KEY
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Run grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Run prometheus
  service:
    name: prometheus
    state: started
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add influxdata key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Influxdb
  apt:
    name: influxdb
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Run influxdb
  service:
    name: influxdb
    state: started
  when: ansible_facts['distribution'] == "Ubuntu"
