---
# tasks file for ubuntuLamp
- name: Install apache2
  apt: 
    name: apache2
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add apache_index
  copy:
    content: "Apache test"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: apache_index
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: apache_index.changed
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Whitelist apache2 in ufw
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install php
  apt:
    name:
       - php
       - php-mysql
       - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add php_index
  copy:
   content: "PHP test"
   dest: /var/www/html/index2.html
   owner: root
   group: root
   mode: '0644'
  when: ansible_facts['distribution'] == "Ubuntu"
